[package]
name = "saw"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.2.1"
libc = "^0.2"
sasm = { git = "https://github.com/savmlang/sa.git" }
savm = { git = "https://github.com/savmlang/sa.git", default-features = false, features = [
  "wasm",
] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"
strip = true
codegen-units = 1
