[build]
target = "wasm32-unknown-emscripten"

[unstable]
build-std = ["core", "alloc", "std", "panic_abort"]

[target.wasm32-unknown-emscripten]
linker = "emcc"
rustflags = [
  # Basic Features
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals,+simd128,+nontrapping-fptoint,+sign-ext,+reference-types",

  # Assume only web, worker
  "-C",
  "link-arg=-sENVIRONMENT=web,worker",

  # 1. #[no_mangle] pub extern "C"
  "-C",
  "link-arg=-sEXPORT_ALL=1",

  # 2. Export JS
  "-C",
  "link-arg=-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','addFunction','removeFunction','getValue','setValue','wasmMemory','wasmTable','HEAP8','HEAP16','HEAP32','HEAP64','HEAPU8','HEAPU16','HEAPU32','HEAPU64','HEAPF32','HEAPF64','UTF8ToString','stringToUTF8','lengthBytesUTF8','UTF16ToString','stringToUTF16','UTF32ToString','stringToUTF32','AsciiToString','stringToAscii','intArrayFromString','intArrayToString','stackSave','stackAlloc','stackRestore','writeArrayToMemory','FS']",

  # 3. WebAssembly runtime
  "-C",
  "link-arg=-sNO_EXIT_RUNTIME=1",

  # 4. ES6
  "-C",
  "link-arg=-sEXPORT_ES6=1",
  "-C",
  "link-arg=-sMODULARIZE=1",
  "-C",
  "link-arg=-sEXPORT_NAME=createSawModule",

  # 5. saw.d.ts
  "-C",
  "link-arg=--emit-tsd=saw.d.ts",

  # 6. Memory
  "-C",
  "link-arg=-sALLOW_MEMORY_GROWTH=1",
  "-C",
  "link-arg=-sINITIAL_MEMORY=33554432",   # 32 MB
  "-C",
  "link-arg=-sMAXIMUM_MEMORY=2147483648", # 2048 MB
  "-C",
  "link-arg=-sWASM_BIGINT",
  "-C",
  "link-arg=-sABORTING_MALLOC=0",
  "-C",
  "link-arg=-fwasm-exceptions",

  # 7. Threading
  "-C",
  "link-arg=-pthread",
  "-C",
  "link-arg=-sPTHREAD_POOL_SIZE=0",
  "-C",
  "link-arg=-sPTHREAD_POOL_SIZE_STRICT=0",
  "-C",
  "link-arg=-sPROXY_TO_PTHREAD=0",

  # 8. Callbacks
  "-C",
  "link-arg=-sALLOW_TABLE_GROWTH=1",
]
