[build]
target = "wasm32-unknown-emscripten"

[unstable]
build-std = ["core", "alloc", "std", "proc_macro", "panic_abort"]

[target.wasm32-unknown-emscripten]
linker = "emcc"
rustflags = [
  # Basic Features
  "-C",
  "target-feature=+atomics,+bulk-memory,+mutable-globals,+simd128,+nontrapping-fptoint,+sign-ext,+reference-types",

  # Assume only web, worker
  "-C",
  "link-arg=-sENVIRONMENT=web,worker",

  # 1. Automatically export EVERY #[no_mangle] pub extern "C" function!
  "-C",
  "link-args=-sEXPORT_ALL=1",

  # 2. Export JS runtime methods (malloc/free for runbox, views, string/pointer helpers)
  "-C",
  'link-args=-sEXPORTED_RUNTIME_METHODS=["ccall","cwrap","getValue","setValue","UTF8ToString","stringToUTF8"]',

  # 3. Keep the WebAssembly runtime alive after initialization
  "-C",
  "link-args=-sNO_EXIT_RUNTIME=1",

  # 4. Export as a modularized ES6 JS library
  "-C",
  "link-args=-sEXPORT_ES6=1",
  "-C",
  "link-args=-sMODULARIZE=1",
  "-C",
  "link-args=-sEXPORT_NAME=createSawModule",

  # 5. Automatically generate TypeScript definitions (`saw.d.ts`)
  "-C",
  "link-args=--emit-tsd=../saw.d.ts",

  # 6. Memory & Exception Configuration
  "-C",
  "link-args=-sALLOW_MEMORY_GROWTH=1",
  "-C",
  "link-args=-sINITIAL_MEMORY=33554432",   # 32 MB
  "-C",
  "link-args=-sMAXIMUM_MEMORY=2147483648", # 2048 MB
  "-C",
  "link-args=-sWASM_BIGINT",
  "-C",
  "link-args=-sABORTING_MALLOC=0",
  "-C",
  "link-args=-fwasm-exceptions",

  # 7. Threading
  "-C",
  "link-arg=-pthread",
  "-C",
  "link-arg=-sPTHREAD_POOL_SIZE=navigator.hardwareConcurrency",
  "-C",
  "link-arg=-sPTHREAD_POOL_SIZE_STRICT=0",
  "-C",
  "link-arg=-sPROXY_TO_PTHREAD=1",
]
