name: Test Build SaVM EMSDK

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup NodeJS
        uses: actions/setup-node@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: wasm32-unknown-emscripten
          components: rust-src

      - name: Setup & Build
        run: |
          bash ./setup.sh
          bash ./build.sh --release

      - name: Copy files to Root
        run: |
          find ./target/wasm32-unknown-emscripten/release -name "saw.d.ts" -exec cp {} . \;
          cp ./target/wasm32-unknown-emscripten/release/saw.js .
          cp ./target/wasm32-unknown-emscripten/release/saw.wasm .

          node patch.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: saw
          archive: true
          compression-level: 9
          path: |
            saw.d.ts
            saw.js
            saw.wasm
