name: Test Build SaVM EMSDK

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    permissions:
      contents: write
      artifact-metadata: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup NodeJS
        uses: actions/setup-node@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: wasm32-unknown-emscripten
          components: rust-src

      - name: Setup & Build
        run: |
          bash ./setup.sh
          bash ./build.sh --release

      - name: Copy files to Root
        run: |
          find ./target/wasm32-unknown-emscripten/release -name "saw.d.ts" -exec cp {} . \;
          cp ./target/wasm32-unknown-emscripten/release/saw.js .
          cp ./target/wasm32-unknown-emscripten/release/saw.wasm .

          node patch.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: saw
          archive: true
          compression-level: 9
          path: |
            saw.d.ts
            saw.js
            saw.wasm

  site:
    name: Build Site

    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [build]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup NodeJS
        uses: actions/setup-node@v7

      - name: Place SaVM WASM
        uses: actions/download-artifact@v8
        with:
          skip-decompress: false
          name: saw
          path: ${{ github.workspace }}/web/public/savm/

      - name: Install & Build
        working-directory: web
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./web/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
